name: FE CI PROD

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI - Build & Upload as Archive
    runs-on: ubuntu-latest

    steps:
      - name: Set Version Timestamp
        run: echo "VERSION=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Generate .env
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_PROD_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Compress Build Files
        run: |
          tar -czf build.tar.gz .next public package.json pnpm-lock.yaml next.config.ts .env

      - name: Upload Archive to GCP
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_PROD_HOST }} \
            "mkdir -p /home/ubuntu/deploy/fe/${{ env.VERSION }}"

          scp -i key.pem -o StrictHostKeyChecking=no build.tar.gz \
            ubuntu@${{ secrets.YOUTIL_PROD_HOST }}:/home/ubuntu/deploy/fe/${{ env.VERSION }}/

      - name: Extract Archive on GCP
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_PROD_HOST }} "
            cd /home/ubuntu/deploy/fe/${{ env.VERSION }} && \
            tar -xzf build.tar.gz && rm build.tar.gz
          "

      - name: Link Latest on Server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_PROD_HOST }} "
            ln -sfn /home/ubuntu/deploy/fe/${{ env.VERSION }} /home/ubuntu/deploy/fe/latest
          "

      - name: Clean Old Versions on Server
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_PROD_HOST }} "bash /home/ubuntu/scripts/fe/clear.sh"
