name: FE Docker CD Prod

on:
  workflow_run:
    workflows: ["FE Docker CI PROD"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=asia-northeast3-docker.pkg.dev/youtil-459908/youtil-docker-registry/youtil-fe-prod:latest" >> $GITHUB_ENV

      - name: Prepare SSH Keys
        run: |
          echo "${{ secrets.YOUTIL_PROD_SSH_KEY }}" > prod_key.pem
          echo "${{ secrets.YOUTIL_BASTION_SSH_KEY }}" > bastion_key.pem
          chmod 600 prod_key.pem bastion_key.pem

      - name: Deploy via SSH Tunnel
        run: |
          # Create SSH tunnel through bastion host
          ssh -i bastion_key.pem -o StrictHostKeyChecking=no -N -L 2222:${{ secrets.YOUTIL_PROD_HOST }}:22 ubuntu@${{ secrets.YOUTIL_BASTION_HOST }} &
          TUNNEL_PID=$!
          
          # Wait for tunnel to establish
          sleep 5
          
          # Execute commands through the tunnel
          ssh -i prod_key.pem -o StrictHostKeyChecking=no -p 2222 ubuntu@localhost << EOF
            docker pull $IMAGE_TAG

            docker stop youtil-fe-prod || true
            docker rm youtil-fe-prod || true

            docker run -d --name youtil-fe-prod \
              -p 3000:3000 \
              $IMAGE_TAG
          EOF
          
          # Clean up tunnel
          kill $TUNNEL_PID
