name: FE Docker CD Prod GCP

on:
  workflow_run:
    workflows: ["FE Docker CI Prod GCP"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GCP VM
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Tag
        run: echo "IMAGE_TAG=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-fe-prod:latest" >> $GITHUB_ENV

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.YOUTIL_DEV_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.YOUTIL_PROD_HOST }} << EOF
            docker pull $IMAGE_TAG

            docker stop youtil-fe-prod || true
            docker rm youtil-fe-prod || true

            docker run -d --name youtil-fe-prod \
              -p 3000:3000 \
              -e NODE_OPTIONS="--max-old-space-size=4096" \
              $IMAGE_TAG
          EOF
