name: FE Docker CI Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js (for PNPM)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Set Docker Image Tag
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          IMAGE=asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/youtil-docker-registry/youtil-fe-dev
          echo "IMAGE_TAG=${IMAGE}:${TIMESTAMP}" >> $GITHUB_ENV
          echo "IMAGE_LATEST=${IMAGE}:latest" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GCP Artifact Registry
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Create .env.production file
        run: echo "${{ secrets.ENV_DEV }}" > .env

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_LATEST }} .

      - name: Push Docker Images
        run: |
          docker push ${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_LATEST }}
