name: Deploy to Cloud Run

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: youtil-459908

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy web-server \
            --image gcr.io/youtil-459908/web-server \
            --region asia-northeast3 \
            --platform managed \
            --allow-unauthenticated
